### ISSUE TITLE
TAP get wrong DHCP IP instead of VPN IP

### ISSUE THREAD

**Issue by kesnol** [openconnect/openconnect-gui#106]
Hello
I have installed openconnect-gui 1.3 in 4 windows7 computers. 2 of them work properly but in the other 2 the TAP interface try to get a DHCP IP and fails.

The connection is established and a right IP is showed in the "VPN Info" tab but ipconfig shows a diferent IP, one in range 169.*

**Comment by horar** [comment]
Hello, thanks for report; may be give us more info like:
- all installation are running with the same locales/language?
- all users have the same privileges and they start te app in the same way?
- log output could be fine
Thanks! :)

**Comment by BitExodus** [comment]
Exactly same error as @kesnol here. It happens with openconnect-gui 1.3 and also with the openconnect v7.06 cross compiled from sources.

**Comment by BitExodus** [comment]
Checked right now, also happening with openconnect master branch, so I suppose it is not a problem with openconnect-gui, but instead the problem is in openconnect itself.

**Comment by BitExodus** [comment]
Error cause narrowed. Debugging the javascript for network interface configuration I executed the exact same command in a Windows console. It failed with an error (element not found). A quick google search showed some people which gets this error for the command (not related with openconnect, just the command itself) solved it in two different ways, using the interface number instead of the interface name or changing the interface name; as a workaround I used the last approach and change the interface name from "Conexión de área local 2" to "TapDevice". The IP for the device seems OK now.

**Comment by horar** [comment]
thanks (that was a reason I asked for locale/language).
The problem should be fixed in actual development gui version by #87 pull request.
It will be published with next release v1.4. For now, you can get last version of script from 'devel' branch and drop them into your installation.

**Comment by kesnol** [comment]
Hello all.
In my case the four computers have installed a Windows 7 Professional COE image, all them are in english, no other language is available.
Our users are local administrators so it can not be a permissions problem.

We have tried to rename the NIC as "TapDevice" as @BitExodus said but it did't work.

The log contains IP's, domains and routes, that I don't want to publish. I will try to clear one and attach it.

**Comment by kesnol** [comment]
The last computer still not working it seems a problem with McAfee. The security is harder in this computer and we have no permissions to change it. This computer doesn't run the js, no log is created.

**Comment by horar** [comment]
openconnect issue should be fixed by mentioned javascript, release in v1.4.0; I don't know what we can do with McAfee (?)

**Comment by sssimha** [comment]
Hi @horar ,

I'm running an ocserv on my home network as I use it a lot to store my work and personal files. I've been able to use the gui to connect to the VPN but the TAP windows adapter does not seem to get the IP.

I'm not sure how to ensure that the js file is run when connecting, presuming that the js file runs automatically. I am on a Windows 10 machine. What can I look for in the logs to validate that the js file is run.

**Comment by sssimha** [comment]
Never mind @horar , i just saw this https://github.com/openconnect/openconnect-gui/issues/193#issuecomment-370039794
