### ISSUE TITLE
v1.4.1 and previous (Win 10 x64) Tunnel UP, but no traffic

### ISSUE THREAD

**Issue by UltimatPronin** [openconnect/openconnect-gui#132]
Client connects & show green light, but 0 received bytes in network activity.
VPN tunnel is up & configured, but no traffic in it.

I try to compare outputs of "route print -4" commands with openconnect & official CISCO client.
Outputs are the same.

TAP-Windows Adapter V9 status is: "Unidentified network", no network access.
In log I can see:
Got DTLS DPD response
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS0.9)-(RSA)-(AES-128-CBC)-(SHA1).
Send CSTP Keepalive
Send DTLS Keepalive
Send CSTP DPD
Got CSTP DPD response
...

Whats wrong?
Maybe more info is needed?

P.S.: using version 1.3 only 1 time I get traffic in VPN tunnel. Others times the same picture with no traffic.

**Comment by slcpunk** [comment]
I've got the same issue.  Not smart enough to really know why, but seems like routing is broken.  ( I can even see routes added in log )  Maybe default gateway is broken?  Not sure.  Windows 7, and OC1.41.

Happy to provide any logs/output if it would help.

**Comment by horar** [comment]
May be attach whole log (just obfuscate 'Set-Cookie' content). Pls. close-open log window (there is a bug with loading vpnc script output).

**Comment by UltimatPronin** [comment]
Here is my log, but I dont see 'Set-Cookie' in it:[Log.txt](https://github.com/openconnect/openconnect-gui/files/451344/Log.txt)

**Comment by UltimatPronin** [comment]
The same situation on Windows 7 and other Windows 10 PC. Any ideas?

**Comment by horar** [comment]
could you please try openconnect.exe console client available with 1.4.1 gui release?
(just start via console with admin rights), thanks

**Comment by UltimatPronin** [comment]
The same result =(

In console I see "connected" message, but TAP-Windows Adapter V9 status is: "Unidentified network", no network access.
...
 CSTP Ciphersuite: (TLS1.0)-(DHE-RSA-1024)-(AES-128-CBC)-(SHA1)
 Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

Opened tun device Ethernet 2
 TAP-Windows driver v9.21 (0)
 Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

Connected Ethernet 2 as XXX.YYY.ZZZ.TTT, using SSL
 Send CSTP Keepalive
 Send CSTP DPD
 Got CSTP DPD response
 Send CSTP Keepalive
...

**Comment by UltimatPronin** [comment]
Any ideas?

**Comment by slcpunk** [comment]
Here's my log.  I am connected, it seems to me that the routing for the vpn network just isn't added ( although I see entries in the routing table...but who knows )

When I ping an IP that should be available, I can see that it is getting sent back out over the regular network adapter instead of being sent out over the VPN adapter.  (so for example, in my case any 10.24.x.x address should be routed over the VPN, but instead it seems to be sent out to the internet like any other address )

sorry, I wish I was smarter and knew more.  Anyway, let me know I can try to test in different ways too.

I saw the message about "unable to spawn" the vpn script.  Not sure about that.  The script file exists at that path.

[openconnect-log.txt](https://github.com/openconnect/openconnect-gui/files/457930/openconnect-log.txt)

**Comment by slcpunk** [comment]
Hey!  I don't know how to fix it, but just think I spotted what the problem is, at least in my case.  The route is getting added, but the wrong INTERFACE is being used for the route.  So the VPN TAP adapter is not being used, instead the regular NIC is set as the interface.  Can see it my route print here:

    10.24.0.0      255.255.0.0        10.9.26.6     192.168.0.22 

That last IP should be the VPN device ( something like 10.9.26.5 )  the 192 is my regular NIC address.

At least I think that's what's wrong...right?
![selection_486](https://cloud.githubusercontent.com/assets/5738127/18367323/dc3e641e-75d7-11e6-8da4-dd0ae78e5a46.jpg)
[route_print.txt](https://github.com/openconnect/openconnect-gui/files/462730/route_print.txt)

**Comment by UltimatPronin** [comment]
No any news about this bug?

**Comment by horar** [comment]
Looks like the TAP setup is incomplete. if we get green light and no traffic; it mostly indicate that 'vpnc-script.js' script fails.

Looking to attached log, the line: "<<-- [EXEC] netsh interface ip add dns "50" 10.25.4.38 index=1"
doesn't have corespond '-->> (ret: 0)' part.

Could you please look closer to this script or may be better to 'function exec(cmd)', may be it fails somehow...

**Comment by UltimatPronin** [comment]
In My case, all (ret: 0)' parts is in needed place.
I don't understand what to try or to check more?

**Comment by UltimatPronin** [comment]
Looks like TAB driver bug or I not understand what described in this thead?
[Here it is](http://openconnect-devel.infradead.narkive.com/LIr2Ws4W/openconnect-v7-06-for-windows-issue#post4).

**Comment by AriaShishegaran** [comment]
I've installed it using Streisand on DigitalOcean. it works perfectly on Android 7 on nexus 6p. the same thing doesn't work on windows 10 x64 anniversary edition. it shows 6-10 Kb of upload and zero downloads and remains that way. also, I'm getting an error on my browser saying my internet is blocked! and I need to check my firewall or similar software which I've never faced before.
so I'm connected, my IP doesn't change (how do I know that when I'm not connected? it connects to google, and yahoo but not others! when I search my IP, it's the same, the blocked websites don't open, the rest are blocked or restricted for no reason and I've tried it on different browsers).

-do you have the same set of problems?

**Comment by UltimatPronin** [comment]
In my case on 3 different PC running under Windows 10 and 7 it shows only upload KB and zero downloads, but also CONNECTED and TAP tuned. No have others yours problems.

**Comment by AriaShishegaran** [comment]
@UltimatePronin ok, that's the main problem. Were you able to connect using previous versions? 
1.3 doesnt work for me as well, green lock is displayed on both versions but none of them connect. Does sending my log file help?

**Comment by UltimatPronin** [comment]
1.3 also no work (((( and command line openconnect not work too.

**Comment by horar** [comment]
if the problem is reproducible with command line tool as well, does someone ask on ['openconnect' mailing list](http://www.infradead.org/openconnect/mail.html) ? I'm not sure how many that developers follow this GUI issues

**Comment by dwmw2** [comment]
Thanks for bringing this to the mailing list. The problem is that Windows *really* wants its network adapters to behave like Ethernet, and doesn't really handle point-to-point devices very well. Or indeed at all.

So need to configure it with a subnet, and the TAP-Windows adapter actually has code inside it to respond to ARP requests for the "router" on that subnet. If we have a netmask of 255.255.255.255 there *are* no other addresses within that subnet, the TAP-Windows driver never fakes ARP responses, and Windows will never manage to communicate.

Note that here we're talking about the configuration of the device itself; the routing set up by vpnc-script-win.js for what addresses Windows will route to this adapter is entirely separate.

One nasty trick we could use (and @UltimatPronin has confirmed that it works on the device side) is to clear the bottom bit of the netmask when we configure the device. So the netmask would never be smaller than 255.255.255.254, and that means that for any given IP address a.b.c.d, the address a.b.c.(d^1) would always be responding to ARP as far as Windows is concerned.

The problem is that a.b.c.(d^1) might be a valid IP address that you need to talk to that *isn't* on the VPN. That's kind of why you were given the 255.255.255.255 netmask in the first place; to indicate that the other surrounding IP addresses are *not* included.

But we could probably make this work. Note that vpnc-script-win.js currently assumes that it can use the IP address a.b.c.(d+1) as "another address on the subnet", which is wrong and wants changing to a.b.c.(d^1) if we do it this way.

However, 255.255.255.254 isn't really a valid Ethernet netmask, although it suffices to trick the TAP-Windows adapter. Remember, the first subnet address (all zeroes) and the last subnet address (all ones) are the network and broadcast address respectively, and cannot be used for stations. So there are technically no *usable* IP addresses in an Ethernet segment with that netmask. And when it comes to actually setting up *routing*, Windows will disallow that.
It's more fun than that; in testing, @UltimatPronin had an address of a.b.c.47. And for that, we couldn't use a netmask smaller than 255.255.255.224 — because for any smaller netmask, that address .47 would have been the broadcast address for such an Ethernet segment, and Windows didn't allow the routing to be set up like that. But I believe you did eventually get it to work, by using different settings for `REDIRECT_GATEWAY_METHOD` in the script?

The TAP-Windows driver also has a 'point to point' mode, where the "other address" on the subnet doesn't need to be adjacent to the client's own IP address. So perhaps we could use that to avoid abusing the a.b.c.(d^1) address as above.There are issues with doing that too; firstly that at this point it's non-trivial for OpenConnect to *know* what another IP address on the VPN would be. But I suppose we *could* go grubbing through any split-include settings to find an address. And we could export that address in a new environment variable so that the script can configure things to route via that.

But... can Windows even handle the concept of a routing for a point-to-point Ethernet interface, or would we have to configure the routing with a subnet that includes the client and "other" IP addresses anyway?

It would be great if someone who actually knows and cares about Windows networking could take a look at this. For a start, what happens with OpenVPN when a Windows client is asked to configure a point-to-point connection with a client address of 1.2.3.4 and a server address on the VPN of 5.6.7.8?

**Comment by dwmw2** [comment]
Looking at the OpenVPN documentation, they explicitly tell you not to use the p2p topology when you might have Windows clients, and instead to use a subnet no smaller than a /30. So I don't think we'll get any help there.

But I'm told the official Cisco client *does* cope with this setup... can anyone show information about the routing when it is connected in such a configuration? Are they just abusing the adjacent IP addresses, in the way that I was unhappy above above? Or is there some extra magic you can do to make Windows actually cope with a point-to-point link?

**Comment by UltimatPronin** [comment]
With official client we have 100% the same routes. "Magic" in client )))

**Comment by dwmw2** [comment]
Can you show an example, please? And also are you able to take a packet capture when you communicate with something on the VPN? Is there fake-ARP happening?

**Comment by UltimatPronin** [comment]
Here is my routes. May be it helps your to understand wtf happen.
But I don't know how to dump arp traffic on Windows 10, sorry.

If you know how to do this - I can try it later.


>Пятница, 23 сентября 2016, 18:19 +03:00 от dwmw2 <notifications@github.com>:
>
>Can you show an example, please? And also are you able to take a packet capture when you communicate with something on the VPN? Is there fake-ARP happening? 
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


===========================================================================
Interface List
  7...00 ff 8e 50 58 70 ......TAP-Windows Adapter V9
 10...10 1f 74 ff a4 7b ......Intel(R) 82579LM Gigabit Network Connection
  4...08 11 96 75 1c ad ......Microsoft Wi-Fi Direct Virtual Adapter
  8...08 11 96 75 1c ac ......Intel(R) Centrino(R) Advanced-N 6205
  1...........................Software Loopback Interface 1
 31...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter
 32...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.0.1     192.168.0.71     55
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
      192.168.0.0    255.255.255.0         On-link      192.168.0.71    311
     192.168.0.71  255.255.255.255         On-link      192.168.0.71    311
    192.168.0.255  255.255.255.255         On-link      192.168.0.71    311
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link      192.168.0.71    311
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link      192.168.0.71    311
===========================================================================
Persistent Routes:
	None
===========================================================================
===========================================================================
Interface List
  5...00 05 9a 3c 7a 00 ......Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows
  7...00 ff 8e 50 58 70 ......TAP-Windows Adapter V9
 10...10 1f 74 ff a4 7b ......Intel(R) 82579LM Gigabit Network Connection
  4...08 11 96 75 1c ad ......Microsoft Wi-Fi Direct Virtual Adapter
  8...08 11 96 75 1c ac ......Intel(R) Centrino(R) Advanced-N 6205
  1...........................Software Loopback Interface 1
 31...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter
 32...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
 37...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #2
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.0.1     192.168.0.71     55
          0.0.0.0          0.0.0.0    2.248.106.137    2.248.106.136      2
    2.248.106.136  255.255.255.255         On-link     2.248.106.136    257
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
    AAA.BBB.CCC.74  255.255.255.255      192.168.0.1     192.168.0.71     56
      192.168.0.1  255.255.255.255         On-link      192.168.0.71     56
     192.168.0.71  255.255.255.255         On-link      192.168.0.71    311
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link      192.168.0.71    311
        224.0.0.0        240.0.0.0         On-link     2.248.106.136    257
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link      192.168.0.71    311
  255.255.255.255  255.255.255.255         On-link     2.248.106.136    257
===========================================================================
Persistent Routes:
  Network Address          Netmask  Gateway Address  Metric
          0.0.0.0          0.0.0.0    2.248.106.137       1
===========================================================================
===========================================================================
Interface List
  7...00 ff 8e 50 58 70 ......TAP-Windows Adapter V9
 10...10 1f 74 ff a4 7b ......Intel(R) 82579LM Gigabit Network Connection
  4...08 11 96 75 1c ad ......Microsoft Wi-Fi Direct Virtual Adapter
  8...08 11 96 75 1c ac ......Intel(R) Centrino(R) Advanced-N 6205
  1...........................Software Loopback Interface 1
 31...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter
 32...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
 37...00 00 00 00 00 00 00 e0 Microsoft ISATAP Adapter #2
===========================================================================

IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.0.1     192.168.0.71     55
          0.0.0.0          0.0.0.0     2.248.96.175     2.248.96.174      2
     2.248.96.174  255.255.255.255         On-link      2.248.96.174    257
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
        127.0.0.1  255.255.255.255         On-link         127.0.0.1    331
  127.255.255.255  255.255.255.255         On-link         127.0.0.1    331
    AAA.BBB.CCC.73  255.255.255.255      192.168.0.1     192.168.0.71     56
    AAA.BBB.CCC.74  255.255.255.255      192.168.0.1     192.168.0.71     56
      192.168.0.0    255.255.255.0         On-link      192.168.0.71    311
     192.168.0.71  255.255.255.255         On-link      192.168.0.71    311
    192.168.0.255  255.255.255.255         On-link      192.168.0.71    311
        224.0.0.0        240.0.0.0         On-link         127.0.0.1    331
        224.0.0.0        240.0.0.0         On-link      192.168.0.71    311
        224.0.0.0        240.0.0.0         On-link      2.248.96.174    257
  255.255.255.255  255.255.255.255         On-link         127.0.0.1    331
  255.255.255.255  255.255.255.255         On-link      192.168.0.71    311
  255.255.255.255  255.255.255.255         On-link      2.248.96.174    257
===========================================================================
Persistent Routes:
  Network Address          Netmask  Gateway Address  Metric
          0.0.0.0          0.0.0.0     2.248.96.175       1
===========================================================================

**Comment by dwmw2** [comment]
I think I might have this working. I've changed OpenConnect to set network and mask to 0.0.0.0 on the TAP adapter. Which again, isn't about the routing — it just means that the device driver will fake ARP requests for *any* IP address which Windows attempts to send to. Which means that we can add any IP address we like as an 'On-link' route, instead of needing that nonsense about a.b.c.(d^1) IP addresses.

I've been able to manually configure the interface with point-to-point addressing, like this:
```
netsh interface ip set address "tun" status 172.31.255.101
route add 172.31.255.1 mask 255.255.255.255 0.0.0.0 if 28
```
That gives me a point-to-point link with 172.31.255.101 as the local address, and 172.31.255.1 as the remote. We should be able to add as many remote IP addresses and networks as we like.
This was tested on Windows 8.1.

Anyone want to update vpnc-script-win.js to do this? I can provide a test account with point-to-point routing.

**Comment by dwmw2** [comment]
I've added a $TUNIDX environment variable for the benefit of the script:
http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/6096fb0e49

**Comment by 4t0m1k** [comment]
I'll modify the script in order to accept on-link routes.

I've already modified it so it define a /30 /29 or /28 subnet if the initial subnet is > /30. I've also added the EXLUDE rule for config like @UltimatPronin's.

Try it and tell me if it works (not yet tested).


[vpnc-script-win.js.zip](https://github.com/openconnect/openconnect-gui/files/495035/vpnc-script-win.js.zip)

**Comment by dwmw2** [comment]
Thanks for looking at this. I don't think your version is quite right though.

You don't need to make it use a larger subnet; using /32 is just fine. All additional routes, including the default route if you want it, can be added with `if $TUNIDX` as in my example above. They become on-link routes. Theoretically, you could ditch the `internal_gw` for routing altogether.

However, using on-link routes is *slightly* suboptimal because Windows will be doing a new ARP lookup (answered by the TAP device driver itself) for *every* IP address it tries to talk to. So where you *can*, you should probably tell Windows that it isn't an on-link route. If it thinks it's routing through some `internal_gw`, then it'll only do ARP for that, and then just send packets to that MAC address. So the logic would look like this...

- Configure the interface with exactly the provided netmask *(even if it's /31 or /32)*.
- *if* the netmask is wider than /31, set `internal_gw` but the last byte should be `address_array[3] ^ 1` not `+ 1`.
- When adding the routes, use `$internal_gw` as we currently do if it is set. Otherwise use `if $TUNIDX`.

**Comment by hollosyt** [comment]
Would a $100 bounty get this fixed any faster?

**Comment by AriaShishegaran** [comment]
Im willing to give away 5 audiobooks of choice from audibe (any title) if
this gets fixed.

**Comment by hollosyt** [comment]
I'll up it to $200 if we get working split routing in Open Connect. Bitcoin or Paypal.

**Comment by 4t0m1k** [comment]
I've modified the script according to the @dwmw2 tips.
I've tried it in a very restrictif env, so I do not know if it works in many cases, but I think it does.

You can download it here and try : 
[vpnc-script.js.zip](https://github.com/openconnect/openconnect-gui/files/516677/vpnc-script.js.zip)

Decompress the .zip and copy the .js in the OpenConnect folder. A reboot may be needed to make it to work (or a routing table flush).

Tell me if it works. You can donate money to OpenConnect and OpenConnect-Gui projects if you want.

**Comment by dwmw2** [comment]
There is no facility for donating money to the OpenConnect project. I wrote it for the public benefit and have never accepted donations of anything but time, code, documentation and testing.

**Comment by hollosyt** [comment]
Thanks guys, we're testing @4t0m1k 's script right now.

**Comment by hollosyt** [comment]
@4t0m1k Script doesn't work , thanks for trying. We're still trying other stuff.

**Comment by hollosyt** [comment]
Our current workaround is a headless vagrant ubuntu VM running openconnect with IP forwarding. Let me know if anyone needs more details who's stuck in a similar situation.

**Comment by dwmw2** [comment]
Can you describe the failure mode of the script? What does it do, and what should it do differently?

**Comment by hollosyt** [comment]
It never added the default route for the vpn connection. There should have been another 0.0.0.0 route with a lower metric. that never appeared.

**Comment by 4t0m1k** [comment]
Hi @hollosyt can you give me the connection log of openconnect-gui please ? If you have INCLUDE rules, the 0.0.0.0 route is not added because include means "nothing but" whereas EXCLUDE means "everything but" in my opinion.

**Comment by 4t0m1k** [comment]
I've modified the script in order do not care about INCLUDE/EXCLUDE when adding default route. Only the following value can add default route :

```
// How to add the default internal route
// -1 - Do NOT add default route
// 0 - As interface gateway when setting properties (NOT compatible with netmask > /30)
// 1 - As a 0.0.0.0/0 route with a lower metric than the default route
// 2 - As 0.0.0.0/1 + 128.0.0.0/1 routes (override the default route cleanly)
var REDIRECT_GATEWAY_METHOD = -1;
```

Changing REDIRECT_GATEWAY_METHOD to 1 should add a 0.0.0.0 route with low metric that override the default route. I think that value 2 is recommended.

New script version : 
[vpnc-script.js.zip](https://github.com/openconnect/openconnect-gui/files/517282/vpnc-script.js.zip)

Please Give me the log for the 2 scripts.

**Comment by 4t0m1k** [comment]
New version :
[vpnc-script.js.zip](https://github.com/openconnect/openconnect-gui/files/518309/vpnc-script.js.zip)

```
// How to add the default internal route
// -1 - Do NOT add default route
// 0 - Add the default route if there's no INCLUDE rule
// 1 - As interface gateway when setting properties (NOT compatible with netmask > /30)
// 2 - As a 0.0.0.0/0 route with a lower metric than the default route
// 3 - As 0.0.0.0/1 + 128.0.0.0/1 routes (override the default route cleanly)
var REDIRECT_GATEWAY_METHOD = 0;
```

I've also added the deletion of routes on disconnect.

**Comment by davidbruce** [comment]
@4t0m1k I used the new scrip three times with the REDIRECT_GATEWAY_METHOD set to 0, 1 and 2.  I was still unable to ping/connect to anything once I connected to VPN.  I've attached the log.  
[openconnect log.txt](https://github.com/openconnect/openconnect-gui/files/519734/openconnect.log.txt)

Thank you very much for your time!

**Comment by 4t0m1k** [comment]
@davidbruce You give me the log with REDIRECT_GATEWAY_METHOD = 1 which is not compatible with netmask > /30.

`Netmask 255.255.255.255 not compatible with REDIRECT_GATEWAY_METHOD = 1, please change the value in the script.`

Please, give me the log with REDIRECT_GATEWAY_METHOD = 0 and 2.

**Comment by davidbruce** [comment]
I've attached the logs for REDIRECT_GATEWAY_METHOD 0 and 2.
[openconnect-log-redirect-gateway-2.txt](https://github.com/openconnect/openconnect-gui/files/519972/openconnect-log-redirect-gateway-2.txt)
[openconnect-log-redirect-gateway-0.txt](https://github.com/openconnect/openconnect-gui/files/519973/openconnect-log-redirect-gateway-0.txt)

**Comment by 4t0m1k** [comment]
Ok thank you.

I think that On-link routes are a bad idea because it will ARP request for each new connection, and TAP-Windows does not forward ARP in tun mode. I think that the adapter make a fake ARP response only if the request concerns the local subnet. Which is not the case with a /32 netmask.

I've modified the script, now if the netmask is > /30, it'll use a fake gateway ip and mac address outside the subnet. Then add the entry in the ARP table for this gateway (default is 169.254.1.1 / 02-ff-ff-ff-ff-ff) and add the routes according to this gateway. This way the ARP request is done locally and only for the gateway address. Data are correctly sent to the tun adapter.

Test it and give me the log please :)

[vpnc-script.js.zip](https://github.com/openconnect/openconnect-gui/files/521256/vpnc-script.js.zip)

I don't know if it works for every version of windows or if it's the best solution.

**Comment by davidbruce** [comment]
Here's the new log.  
[openconnect log-oct-11-845.txt](https://github.com/openconnect/openconnect-gui/files/521807/openconnect.log-oct-11-845.txt)

**Comment by dwmw2** [comment]
With the latest OpenConnect we tell the TAP-Windows driver that the local subnet is /0, so it will do ARP responses for anything. The On-link routes will do ARP for each IP instead of only to the "router" but that's not the end of the world.

**Comment by 4t0m1k** [comment]
@davidbruce This log hasn't be done with the latest script from my last response. Did you correctly replaced the vpnc-script.js in the openconnect-gui folder ?

@dwmw2 Ok ! So the script before the last one should work either with the new openconnect version. Maybe the last version is better for performances concerns, but as you said, that's not the end of the world. I don't know when openconnect-gui will release a version with the last openconnect library. Meanwhile, the last script should do the job.

**Comment by horar** [comment]
@4t0m1k hi, I plan to drop next openconnect-gui version till end of this month; and I can include openconnect lib/tool build from head if @dwmw2 feel it's enough stable  :-)
Just point to updated script (or create a pull request) so I can bundle them...

**Comment by 4t0m1k** [comment]
@horar Ok :)

**Comment by dwmw2** [comment]
OpenConnect HEAD is stable enough. I'm just waiting to fix https://github.com/openssl/openssl/pull/1666 in OpenSSL HEAD so that I can commit my existing fix to bring the OpenSSL up to feature parity, and I'll release OpenConnect 7.08.

Please don't do hacks with routing addresses that aren't yours to the VPN. The On-link routes *should* work. If you really want, you can do just one On-link route and then route the rest through an IP on *that* route as their "gateway". But that's complexity for little benefit. It's not like it takes long for the driver itself to respond to an ARP request.

**Comment by 4t0m1k** [comment]
@dwmw2 Yes, for the next version of openconnect, the script form [this post](https://github.com/openconnect/openconnect-gui/issues/132#issuecomment-252486894) will be the good one. The last version with the hack should not be used except for test purposes.

**Comment by dwmw2** [comment]
Can I have that in the form of a patch against the upstream vpnc-scripts repository please? And I'll need to check it sitll does the right thing with vpnc. Perhaps enable the onlink behaviour only if the new `$TUNIDX` variable is set? Or is that how you already did it?

**Comment by 4t0m1k** [comment]
openconnect-gui use a modified version of the original script from vpnc-scripts repo. This version use a getInterfaceId function to get the id from the interface name. As the issue was concerning the gui, i've modified the gui script. I'll modify the original script and send you a patch. What to do if TUNIDX is no set and netmask > 30 ? With or without on-link, the script would not work since on-link routes require the new openconnect version with netmask /0. So maybe a warning message that say to update openconnect and stop the script execution ?

**Comment by horar** [comment]
@4t0m1k actually, as far I know from former discussions, the script in this project is from time-to-time moved back into vpnc-script repo (yes, I don't expect it too), i.e. the windows script here can be the most accurate version. In this case, we don't need be scared to continue (it's just a notice for me, to puclish updated script with newest openconnect)

And yes, we use interfaces id's because there was problems with localized interface names. It was a fix from project contributor/s

**Comment by dwmw2** [comment]
> @4t0m1k actually, as far I know from former discussions, the script in this project is from time-to-time moved back into vpnc-script repo (yes, I don't expect it too), i.e. the windows script here can be the most accurate version. 

Why would you not expect any changes to be merged back into the [upstream repository](http://git.infradead.org/users/dwmw2/vpnc-scripts.git) for vpn-scripts? That should *always* be the place to look for the latest version. People shouldn't need to go looking for changes which might have been made by other people who copy and package the software.

> And yes, we use interfaces id's because there was problems with localized interface names. It was a fix from project contributor/s

No, that isn't why I did it. On Windows we don't have a problem with localised interface names — we can pass it to the vpnc-script as UTF-16. I [fixed that](http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/9736684464165d0127d0e32eb9b4403387c09f82) a long time ago.

The reason I [added `$TUNIDX`](http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/6096fb0e49e6dfed4f6a0f3363d4873e528eabef) was purely to support the Windows method of supporting on-link routes, which requires specifying the interface by its index as discussed above.

It wasn't a fix from a project contributor. I, the original [OpenConnect]( http://www.infradead.org/openconnect/) author and maintainer, did it myself.

**Comment by 4t0m1k** [comment]
The main difference between the 2 script versions is that the script used by the gui standard output goes to a file (tmp_folder/vpnc.log). I will make only one version of the script where there is a constant which define if the output goes to a file or to stdout. It'll make it usable as it by the console executable and by the gui (with the constant set to output=file). I think that every modification of the script should go to the vpnc-script repo after test verifications.

@dwmw2 I send you the patch by e-mail as soon as possible.

**Comment by skoehler** [comment]
I seem to suffer from this issue on Windows 7 (x64). The connection is established, but there's no traffic on the TAP adapter. A default route is in the routing table and has the lowest metric - but it isn't used for some reason.

**Comment by horar** [comment]
>> @4t0m1k actually, as far I know from former discussions, the script in this project is from time-to-time moved back into vpnc-script repo (yes, I don't expect it too), i.e. the windows script here can be the most accurate version. 

> Why would you not expect any changes to be merged back into the [upstream repository](http://git.infradead.org/users/dwmw2/vpnc-scripts.git) for vpn-scripts? That should *always* be the place to look for the latest version. People shouldn't need to go looking for changes which might have been made by other people who copy and package the software.

yes, this will be great...

>> And yes, we use interfaces id's because there was problems with localized interface names. It was a fix from project contributor/s

> No, that isn't why I did it. On Windows we don't have a problem with localised interface names — we can pass it to the vpnc-script as UTF-16. I [fixed that](http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/9736684464165d0127d0e32eb9b4403387c09f82) a long time ago.

could be, pls. look to problem description in #87 , may be ask @esabouraud for more details...

> The reason I [added `$TUNIDX`](http://git.infradead.org/users/dwmw2/openconnect.git/commitdiff/6096fb0e49e6dfed4f6a0f3363d4873e528eabef) was purely to support the Windows method of supporting on-link routes, which requires specifying the interface by its index as discussed above.

> It wasn't a fix from a project contributor. I, the original [OpenConnect]( http://www.infradead.org/openconnect/) author and maintainer, did it myself.

**Comment by rav1ne** [comment]
Hi,
is there any update on this? We are having this problem, client seemingly connects, but the traffic not goes to the right interface. I can't see newer version than the 1.4.1.
Strangely, it worked for a month relatively well, but then my VPS died with the ocserv. After the reboot, nothing works on client side (win8/64 and win10/64).
I've tried with the attached vpnc script, but still no good. I see no errors in the logs.
Thanks

**Comment by rav1ne** [comment]
Uhm, forget it, i guess it's okay now.
I forgot about this tutorial:
https://www.vultr.com/docs/setup-openconnect-vpn-server-for-cisco-anyconnect-on-ubuntu-14-04-x64

I've forgot the iptables line. Is it necessary?

**Comment by 4t0m1k** [comment]
@rav1ne The iptables line enable NAT in order the clients can reach another network on the server (even WAN). If you are using openconnect as a local VPN, don't add the line.

@horar I've modified the script but I've no more access to an openconnect server so I have not tested it. When will you release the new openconnect-gui version ?

**Comment by moralrebuild** [comment]
Four months passed and standing at the end of 2016, I could say the latest version 1.4.1 of openconnect windows client is useless for this issue. Is this project dead?

**Comment by UltimatPronin** [comment]
**moralrebuild**, everything is ok from end of september. But you need to use the latest openconnect release. You can get it [here](https://github.com/horar/openconnect/releases/tag/v7.08) or build from official source.

**Comment by stealthybox** [comment]
Thanks for linking that @UltimatPronin!
@horar's v7.08 build of openconnect works for me from the CLI.
I'm even able to use `--token-mode=rsa` with an `~/.stokenrc` if I run openconnect from an MSYS2 shell like `git-bash` or `msys2:zsh`.

Looks like we need a new build/release for the GUI, though.
Copying the v7.08 DLL's into an openconnect-gui installation causes the program to crash on startup.

For now, I made a shortcut on my taskbar with this target:
`%COMSPEC% /k "zsh -c 'openconnect -u stealthybox --token-mode=rsa vpn.example.com/GROUP'"`
I found a nice networking icon, and it works great!

**Comment by horar** [comment]
I will drop new GUI this week build against v7.08

**Comment by alexanderific** [comment]
@horar any update on a new build?

**Comment by horar** [comment]
@alexanderific win build on the weekend, and macOS build on start of next week;
sorry for delay, find small issue on win but one crash on mac....

**Comment by stealthybox** [comment]
Thank you @horar !

**Comment by grandiego** [comment]
I'm suffering this bug. 
ocserv 0.11.6-1 properly set up and working flawlessly with android, ubuntu and cisco anyconnect windows client.
openconnect-gui 1.5.1 connects, but no traffic in tunnel.

Please request any log or test I could provide to help solving this.

**Comment by davidbruce** [comment]
We have rolled out the updated openconnect-gui to quite a few windows users and it is working well.  Thank you very much @horar!

**Comment by grandiego** [comment]
Finally got it to work.
I had to rename TAP interface from default 'Conexión de área local 2' (Spanish for, you guessed it, 'Local area connection 2') to just 'VPN' and that solved the issue.

Maybe it's related to non-ASCII characters or whitespaces? Probably vnc-script.js needs to wrap interface name in quotes to avoid this...

**Comment by horar** [comment]
yes, there is problem with vpnc script bundled to gui; I'm working no removing some changes and I will try submit relevant logging changes into upstream repo (we have already a ticket for non-ascii chars issue, what is reproducible for me as well, #145)

**Comment by privet971** [comment]
Grandiego's workaround is perfect for the french version too
Thanks a lot.

**Comment by horar** [comment]
I fixed it in vpnc-win script; it was sent for review/integration into upstream vpnc repo; so it should be released with oc-gui 1.6

**Comment by pncampbell** [comment]
Well its October 2017 and I'm still getting this problem on win 10

**Comment by horar** [comment]
@pncampbell it was confirmed the issue was solved. If you face 'this' problem, please share more info with us. It may be completelly different problem with the same result or ...

**Comment by vincenzodnp** [comment]
> I'll modify the script in order to accept on-link routes.
> 
> I've already modified it so it define a /30 /29 or /28 subnet if the initial subnet is > /30. I've also added the EXLUDE rule for config like @UltimatPronin's.
> 
> Try it and tell me if it works (not yet tested).
> 
> [vpnc-script-win.js.zip](https://github.com/openconnect/openconnect-gui/files/495035/vpnc-script-win.js.zip)

Thanks! your script plus 1.5.2, worked like a charme on Windows7 ;)
